from __future__ import annotations

import sqlite3
import os
import json
from contextlib import contextmanager
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable, Any

from adapters import BasketItem, PriceResult, build_adapter_registry

APP_DIR = Path(__file__).resolve().parent
DATA_DIR = APP_DIR / "data"
DB_PATH = DATA_DIR / "price_history.sqlite"
BASKET_PATH = DATA_DIR / "basket.xlsx"
BASELINE_MARKETPLACE = "HaloSkins"
MIN_SNAPSHOT_SUCCESS_RATE = 0.6
MAX_MARKETPLACE_FAILURE_RATE = 0.4
REMOVED_MOCK_ADAPTER_KEYS = {
    "skinswap_mock",
    "csfloat_mock",
    "skinplace_mock",
    "whitemarket_mock",
    "csmoney_mock",
    "shadowpay_mock",
}
REMOVED_MOCK_MARKETPLACES = {
    "SkinSwap Mock",
    "CSFloat Mock",
    "Skin.Place Mock",
    "White.market",
    "CS.Money Mock",
    "ShadowPay Mock",
}


def postgres_database_url() -> str | None:
    value = os.getenv("DATABASE_URL")
    return value.strip() if value and value.strip() else None


def database_url() -> str | None:
    backend = os.getenv("DATABASE_BACKEND", "").strip().lower()
    if backend in {"sqlite", "local"}:
        if running_on_streamlit_cloud() and postgres_database_url() and not force_sqlite():
            return postgres_database_url()
        return None
    return postgres_database_url()


def using_postgres() -> bool:
    return bool(database_url())


def running_on_streamlit_cloud() -> bool:
    return APP_DIR.as_posix().startswith("/mount/src/") or bool(os.getenv("STREAMLIT_CLOUD"))


def force_sqlite() -> bool:
    return os.getenv("CS2DT_FORCE_SQLITE", "").strip().lower() in {"1", "true", "yes", "on"}


def _adapt_sql(sql: str, backend: str | None = None) -> str:
    is_postgres = backend == "postgres" if backend else using_postgres()
    if not is_postgres:
        return sql
    return sql.replace("?", "%s")


class DbConnection:
    def __init__(self, raw, backend: str):
        self.raw = raw
        self.backend = backend

    def execute(self, sql: str, params: Iterable[Any] | None = None):
        return self.raw.execute(_adapt_sql(sql, self.backend), tuple(params or ()))

    def executemany(self, sql: str, params):
        if self.backend == "sqlite":
            return self.raw.executemany(_adapt_sql(sql, self.backend), params)
        with self.raw.cursor() as cur:
            return cur.executemany(_adapt_sql(sql, self.backend), params)

    def executescript(self, sql: str) -> None:
        if self.backend == "sqlite":
            self.raw.executescript(sql)
            return
        for statement in sql.split(";"):
            statement = statement.strip()
            if statement:
                self.raw.execute(statement)

    def commit(self) -> None:
        self.raw.commit()

    def close(self) -> None:
        self.raw.close()


@contextmanager
def connect():
    if using_postgres():
        import psycopg
        from psycopg.rows import dict_row

        con = psycopg.connect(database_url(), row_factory=dict_row)
        wrapped = DbConnection(con, "postgres")
    else:
        DATA_DIR.mkdir(parents=True, exist_ok=True)
        con = sqlite3.connect(DB_PATH, timeout=float(os.getenv("SQLITE_TIMEOUT_SECONDS", "30")))
        con.row_factory = sqlite3.Row
        con.execute(f"PRAGMA busy_timeout = {int(float(os.getenv('SQLITE_TIMEOUT_SECONDS', '30')) * 1000)}")
        con.execute("PRAGMA journal_mode = WAL")
        wrapped = DbConnection(con, "sqlite")
    try:
        yield wrapped
        wrapped.commit()
    finally:
        wrapped.close()


@contextmanager
def connect_postgres():
    url = postgres_database_url()
    if not url:
        raise RuntimeError("DATABASE_URL is not configured.")
    import psycopg
    from psycopg.rows import dict_row

    con = psycopg.connect(url, row_factory=dict_row)
    wrapped = DbConnection(con, "postgres")
    try:
        yield wrapped
        wrapped.commit()
    finally:
        wrapped.close()


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="milliseconds")


def init_db() -> None:
    with connect() as con:
        con.executescript(_schema_sql())
        ensure_column(con, "basket_items", "multiplier", "INTEGER NOT NULL DEFAULT 1")
        ensure_column(con, "basket_items", "price_compare_url", "TEXT")
        ensure_column(con, "basket_items", "priceempire_url", "TEXT")
        ensure_column(con, "basket_items", "steamanalyst_url", "TEXT")
        ensure_column(con, "basket_items", "marketplace_links_json", "TEXT")
        remove_mock_marketplaces(con)
        prune_low_quality_snapshots(con, MIN_SNAPSHOT_SUCCESS_RATE)
    seed_marketplaces()


def _schema_sql(backend: str | None = None) -> str:
    is_postgres = backend == "postgres" if backend else using_postgres()
    if is_postgres:
        return """
            CREATE TABLE IF NOT EXISTS basket_items (
                item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                market_hash_name TEXT NOT NULL UNIQUE,
                active INTEGER NOT NULL DEFAULT 1,
                multiplier INTEGER NOT NULL DEFAULT 1,
                notes TEXT NOT NULL DEFAULT '',
                source_rank INTEGER,
                source_amount DOUBLE PRECISION,
                price_compare_url TEXT,
                priceempire_url TEXT,
                steamanalyst_url TEXT,
                marketplace_links_json TEXT,
                created_at TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS marketplaces (
                adapter_key TEXT PRIMARY KEY,
                name TEXT NOT NULL UNIQUE,
                enabled INTEGER NOT NULL DEFAULT 1,
                is_baseline INTEGER NOT NULL DEFAULT 0,
                requires_credentials INTEGER NOT NULL DEFAULT 0,
                last_status TEXT,
                last_error TEXT,
                updated_at TEXT
            );

            CREATE TABLE IF NOT EXISTS snapshots (
                snapshot_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                timestamp TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS price_points (
                price_point_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                snapshot_id INTEGER NOT NULL REFERENCES snapshots(snapshot_id),
                marketplace TEXT NOT NULL,
                item_id INTEGER REFERENCES basket_items(item_id),
                market_hash_name TEXT NOT NULL,
                price DOUBLE PRECISION,
                currency TEXT NOT NULL DEFAULT 'USD',
                normalized_price DOUBLE PRECISION,
                normalized_currency TEXT NOT NULL DEFAULT 'USD',
                stock_count INTEGER,
                fetch_status TEXT NOT NULL,
                error_details TEXT,
                timestamp TEXT NOT NULL
            );

            CREATE INDEX IF NOT EXISTS idx_price_points_snapshot
                ON price_points(snapshot_id, marketplace);
            CREATE INDEX IF NOT EXISTS idx_price_points_history
                ON price_points(marketplace, timestamp);

            CREATE TABLE IF NOT EXISTS update_runs (
                update_run_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                source TEXT NOT NULL,
                started_at TEXT NOT NULL,
                finished_at TEXT NOT NULL,
                duration_seconds DOUBLE PRECISION NOT NULL,
                status TEXT NOT NULL,
                snapshot_id INTEGER,
                success_rate DOUBLE PRECISION,
                error_details TEXT
            );

            CREATE INDEX IF NOT EXISTS idx_update_runs_started_at
                ON update_runs(started_at);

            CREATE TABLE IF NOT EXISTS display_cache (
                cache_key TEXT PRIMARY KEY,
                snapshot_id INTEGER,
                payload TEXT NOT NULL,
                updated_at TEXT NOT NULL
            );
        """
    return """
        PRAGMA foreign_keys = ON;

        CREATE TABLE IF NOT EXISTS basket_items (
            item_id INTEGER PRIMARY KEY AUTOINCREMENT,
            market_hash_name TEXT NOT NULL UNIQUE,
            active INTEGER NOT NULL DEFAULT 1,
            multiplier INTEGER NOT NULL DEFAULT 1,
            notes TEXT NOT NULL DEFAULT '',
            source_rank INTEGER,
            source_amount REAL,
            price_compare_url TEXT,
            priceempire_url TEXT,
            steamanalyst_url TEXT,
            marketplace_links_json TEXT,
            created_at TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS marketplaces (
            adapter_key TEXT PRIMARY KEY,
            name TEXT NOT NULL UNIQUE,
            enabled INTEGER NOT NULL DEFAULT 1,
            is_baseline INTEGER NOT NULL DEFAULT 0,
            requires_credentials INTEGER NOT NULL DEFAULT 0,
            last_status TEXT,
            last_error TEXT,
            updated_at TEXT
        );

        CREATE TABLE IF NOT EXISTS snapshots (
            snapshot_id INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS price_points (
            price_point_id INTEGER PRIMARY KEY AUTOINCREMENT,
            snapshot_id INTEGER NOT NULL,
            marketplace TEXT NOT NULL,
            item_id INTEGER,
            market_hash_name TEXT NOT NULL,
            price REAL,
            currency TEXT NOT NULL DEFAULT 'USD',
            normalized_price REAL,
            normalized_currency TEXT NOT NULL DEFAULT 'USD',
            stock_count INTEGER,
            fetch_status TEXT NOT NULL,
            error_details TEXT,
            timestamp TEXT NOT NULL,
            FOREIGN KEY(snapshot_id) REFERENCES snapshots(snapshot_id),
            FOREIGN KEY(item_id) REFERENCES basket_items(item_id)
        );

        CREATE INDEX IF NOT EXISTS idx_price_points_snapshot
            ON price_points(snapshot_id, marketplace);
        CREATE INDEX IF NOT EXISTS idx_price_points_history
            ON price_points(marketplace, timestamp);

        CREATE TABLE IF NOT EXISTS update_runs (
            update_run_id INTEGER PRIMARY KEY AUTOINCREMENT,
            source TEXT NOT NULL,
            started_at TEXT NOT NULL,
            finished_at TEXT NOT NULL,
            duration_seconds REAL NOT NULL,
            status TEXT NOT NULL,
            snapshot_id INTEGER,
            success_rate REAL,
            error_details TEXT
        );

        CREATE INDEX IF NOT EXISTS idx_update_runs_started_at
            ON update_runs(started_at);

        CREATE TABLE IF NOT EXISTS display_cache (
            cache_key TEXT PRIMARY KEY,
            snapshot_id INTEGER,
            payload TEXT NOT NULL,
            updated_at TEXT NOT NULL
        );
    """


def ensure_column(con: DbConnection, table: str, column: str, definition: str) -> None:
    if using_postgres():
        row = con.execute(
            """
            SELECT 1
            FROM information_schema.columns
            WHERE table_name = ? AND column_name = ?
            """,
            (table, column),
        ).fetchone()
        columns = {column} if row else set()
    else:
        columns = {row["name"] for row in con.execute(f"PRAGMA table_info({table})").fetchall()}
    if column not in columns:
        con.execute(f"ALTER TABLE {table} ADD COLUMN {column} {_pg_column_definition(definition)}")


def _pg_column_definition(definition: str) -> str:
    if not using_postgres():
        return definition
    return definition.replace("REAL", "DOUBLE PRECISION")


def remove_mock_marketplaces(con: DbConnection) -> None:
    key_placeholders = ",".join("?" for _ in REMOVED_MOCK_ADAPTER_KEYS)
    name_placeholders = ",".join("?" for _ in REMOVED_MOCK_MARKETPLACES)
    con.execute(
        f"DELETE FROM marketplaces WHERE adapter_key IN ({key_placeholders})",
        tuple(REMOVED_MOCK_ADAPTER_KEYS),
    )
    con.execute(
        f"DELETE FROM price_points WHERE marketplace IN ({name_placeholders})",
        tuple(REMOVED_MOCK_MARKETPLACES),
    )


def seed_marketplaces() -> None:
    registry = build_adapter_registry()
    defaults_enabled = {
        "haloskins",
        "csfloat",
        "waxpeer",
        "c5game",
        "dmarket",
        "marketcsgo",
        "openskin_skinport",
        "openskin_buff163",
        "openskin_youpin",
        "openskin_steam",
        "csgoskins_csmoney",
        "csgoskins_lis_skins",
        "csgoskins_aim_market",
        "csgoskins_skin_land",
        "csgoskins_skinbaron",
        "csgoskins_skins_com",
        "csgoskins_exeskins",
        "csgoskins_avan_market",
        "csgoskins_skinvault",
        "csgoskins_uuskins",
        "csgoskins_tradeit",
        "csgoskins_skinplace",
        "csgoskins_shadowpay",
        "csgoskins_skinswap",
    }
    now = utc_now_iso()
    with connect() as con:
        for key, adapter in registry.items():
            con.execute(
                """
                INSERT INTO marketplaces (
                    adapter_key, name, enabled, is_baseline,
                    requires_credentials, updated_at
                )
                VALUES (?, ?, ?, ?, ?, ?)
                ON CONFLICT(adapter_key) DO UPDATE SET
                    name = excluded.name,
                    is_baseline = excluded.is_baseline,
                    requires_credentials = excluded.requires_credentials
                """,
                (
                    key,
                    adapter.name,
                    1 if key in defaults_enabled else 0,
                    1 if adapter.name == BASELINE_MARKETPLACE else 0,
                    1 if adapter.requires_credentials else 0,
                    now,
                ),
            )


def basket_is_empty() -> bool:
    with connect() as con:
        row = con.execute("SELECT COUNT(*) AS c FROM basket_items").fetchone()
        return int(row["c"]) == 0


def _json_or_none(value) -> str | None:
    if not isinstance(value, dict) or not value:
        return None
    clean = {str(key): str(url) for key, url in value.items() if key and url}
    return json.dumps(clean, ensure_ascii=False, sort_keys=True) if clean else None


def _json_to_dict(value) -> dict[str, str]:
    if not value:
        return {}
    try:
        parsed = json.loads(value)
    except (TypeError, ValueError):
        return {}
    if not isinstance(parsed, dict):
        return {}
    return {str(key): str(url) for key, url in parsed.items() if key and url}


def insert_basket_items(rows: Iterable[dict]) -> int:
    now = utc_now_iso()
    count = 0
    with connect() as con:
        for row in rows:
            name = str(row["market_hash_name"]).strip()
            if not name:
                continue
            cur = con.execute(
                """
                INSERT INTO basket_items (
                    market_hash_name, active, multiplier, notes, source_rank,
                    source_amount, price_compare_url, priceempire_url,
                    steamanalyst_url, marketplace_links_json, created_at
                )
                VALUES (?, 1, 1, '', ?, ?, ?, ?, ?, ?, ?)
                ON CONFLICT(market_hash_name) DO UPDATE SET
                    source_rank = COALESCE(excluded.source_rank, basket_items.source_rank),
                    source_amount = COALESCE(excluded.source_amount, basket_items.source_amount),
                    price_compare_url = COALESCE(excluded.price_compare_url, basket_items.price_compare_url),
                    priceempire_url = COALESCE(excluded.priceempire_url, basket_items.priceempire_url),
                    steamanalyst_url = COALESCE(excluded.steamanalyst_url, basket_items.steamanalyst_url),
                    marketplace_links_json = COALESCE(excluded.marketplace_links_json, basket_items.marketplace_links_json)
                """,
                (
                    name,
                    row.get("rank"),
                    row.get("source_amount"),
                    row.get("price_compare_url"),
                    row.get("priceempire_url"),
                    row.get("steamanalyst_url"),
                    _json_or_none(row.get("marketplace_links")),
                    now,
                ),
            )
            if cur.rowcount:
                count += 1
    return count


def get_basket_items(active_only: bool = False) -> list[sqlite3.Row]:
    sql = "SELECT * FROM basket_items"
    if active_only:
        sql += " WHERE active = 1"
    sql += " ORDER BY COALESCE(source_rank, item_id), item_id"
    with connect() as con:
        return list(con.execute(sql).fetchall())


def get_adapter_items() -> list[BasketItem]:
    return [
        BasketItem(
            item_id=int(row["item_id"]),
            market_hash_name=row["market_hash_name"],
            price_compare_url=row["price_compare_url"],
            priceempire_url=row["priceempire_url"],
            steamanalyst_url=row["steamanalyst_url"],
            marketplace_links=_json_to_dict(row["marketplace_links_json"]),
        )
        for row in get_basket_items(active_only=True)
    ]


def update_basket_items(rows: Iterable[dict]) -> None:
    with connect() as con:
        for row in rows:
            con.execute(
                """
                UPDATE basket_items
                SET active = ?, multiplier = ?, notes = ?
                WHERE item_id = ?
                """,
                (
                    1 if row.get("active") else 0,
                    min(1000, max(1, int(row.get("multiplier") or 1))),
                    row.get("notes") or "",
                    int(row["item_id"]),
                ),
            )


def get_marketplaces() -> list[sqlite3.Row]:
    order = "is_baseline DESC, LOWER(name)" if using_postgres() else "is_baseline DESC, name COLLATE NOCASE"
    with connect() as con:
        return list(
            con.execute(
                f"""
                SELECT *
                FROM marketplaces
                ORDER BY {order}
                """
            ).fetchall()
        )


def comparison_inputs_for_snapshot(snapshot_id: int) -> tuple[list[sqlite3.Row], list[sqlite3.Row], list[sqlite3.Row]]:
    marketplace_order = (
        "is_baseline DESC, LOWER(name)" if using_postgres() else "is_baseline DESC, name COLLATE NOCASE"
    )
    with connect() as con:
        items = list(
            con.execute(
                """
                SELECT *
                FROM basket_items
                ORDER BY COALESCE(source_rank, item_id), item_id
                """
            ).fetchall()
        )
        points = list(
            con.execute(
                """
                SELECT pp.*, bi.active, bi.multiplier
                FROM price_points pp
                LEFT JOIN basket_items bi ON bi.item_id = pp.item_id
                WHERE pp.snapshot_id = ?
                ORDER BY pp.marketplace, pp.market_hash_name
                """,
                (snapshot_id,),
            ).fetchall()
        )
        marketplaces = list(
            con.execute(
                f"""
                SELECT *
                FROM marketplaces
                ORDER BY {marketplace_order}
                """
            ).fetchall()
        )
    return items, points, marketplaces


def get_enabled_adapter_keys() -> list[str]:
    order = "is_baseline DESC, LOWER(name)" if using_postgres() else "is_baseline DESC, name COLLATE NOCASE"
    with connect() as con:
        rows = con.execute(
            f"""
            SELECT adapter_key
            FROM marketplaces
            WHERE enabled = 1 OR is_baseline = 1
            ORDER BY {order}
            """
        ).fetchall()
    return [row["adapter_key"] for row in rows]


def update_marketplace_settings(rows: Iterable[dict]) -> None:
    now = utc_now_iso()
    with connect() as con:
        for row in rows:
            enabled = 1 if row.get("enabled") or row.get("is_baseline") else 0
            con.execute(
                """
                UPDATE marketplaces
                SET enabled = ?, updated_at = ?
                WHERE adapter_key = ?
                """,
                (enabled, now, row["adapter_key"]),
            )


def save_snapshot_results(results: Iterable[PriceResult]) -> tuple[int, str]:
    timestamp = utc_now_iso()
    item_map = {row["market_hash_name"]: int(row["item_id"]) for row in get_basket_items()}
    status_by_marketplace: dict[str, list[tuple[str, str | None]]] = {}
    with connect() as con:
        if using_postgres():
            cur = con.execute("INSERT INTO snapshots(timestamp) VALUES (?) RETURNING snapshot_id", (timestamp,))
            snapshot_id = int(cur.fetchone()["snapshot_id"])
        else:
            cur = con.execute("INSERT INTO snapshots(timestamp) VALUES (?)", (timestamp,))
            snapshot_id = int(cur.lastrowid)
        for result in results:
            normalized_price = normalize_to_usd(result.price, result.currency)
            con.execute(
                """
                INSERT INTO price_points (
                    snapshot_id, marketplace, item_id, market_hash_name,
                    price, currency, normalized_price, normalized_currency,
                    stock_count, fetch_status, error_details, timestamp
                )
                VALUES (?, ?, ?, ?, ?, ?, ?, 'USD', ?, ?, ?, ?)
                """,
                (
                    snapshot_id,
                    result.marketplace,
                    item_map.get(result.market_hash_name),
                    result.market_hash_name,
                    result.price,
                    result.currency,
                    normalized_price,
                    result.stock_count,
                    result.fetch_status,
                    result.error_details,
                    timestamp,
                ),
            )
            status_by_marketplace.setdefault(result.marketplace, []).append(
                (result.fetch_status, result.error_details)
            )

        for marketplace, statuses in status_by_marketplace.items():
            status, error = summarize_fetch_status(statuses)
            con.execute(
                """
                UPDATE marketplaces
                SET last_status = ?, last_error = ?, updated_at = ?
                WHERE name = ?
                """,
                (status, error, timestamp, marketplace),
            )
    return snapshot_id, timestamp


def record_update_run(
    *,
    source: str,
    started_at: str,
    finished_at: str,
    duration_seconds: float,
    status: str,
    snapshot_id: int | None = None,
    success_rate: float | None = None,
    error_details: str | None = None,
) -> None:
    safe_source = source if source in {"manual", "automatic", "sync"} else "manual"
    with connect() as con:
        con.execute(
            """
            INSERT INTO update_runs (
                source, started_at, finished_at, duration_seconds, status,
                snapshot_id, success_rate, error_details
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                safe_source,
                started_at,
                finished_at,
                max(0.0, float(duration_seconds)),
                status,
                snapshot_id,
                success_rate,
                _none_if_blank(error_details),
            ),
        )


def update_runs(limit: int = 200) -> list[sqlite3.Row]:
    with connect() as con:
        return list(
            con.execute(
                """
                SELECT update_run_id, source, started_at, finished_at, duration_seconds,
                    status, snapshot_id, success_rate, error_details
                FROM update_runs
                ORDER BY started_at DESC, update_run_id DESC
                LIMIT ?
                """,
                (limit,),
            ).fetchall()
        )


def get_display_cache(cache_key: str) -> sqlite3.Row | None:
    with connect() as con:
        return con.execute(
            """
            SELECT cache_key, snapshot_id, payload, updated_at
            FROM display_cache
            WHERE cache_key = ?
            """,
            (cache_key,),
        ).fetchone()


def save_display_cache(cache_key: str, snapshot_id: int | None, payload: str) -> None:
    with connect() as con:
        con.execute(
            """
            INSERT INTO display_cache(cache_key, snapshot_id, payload, updated_at)
            VALUES (?, ?, ?, ?)
            ON CONFLICT(cache_key) DO UPDATE SET
                snapshot_id = excluded.snapshot_id,
                payload = excluded.payload,
                updated_at = excluded.updated_at
            """,
            (cache_key, snapshot_id, payload, utc_now_iso()),
        )


def prune_low_quality_snapshots(
    con: DbConnection,
    min_success_rate: float = MIN_SNAPSHOT_SUCCESS_RATE,
) -> int:
    rows = con.execute(
        """
        SELECT
            s.snapshot_id,
            COUNT(pp.price_point_id) AS total_count,
            SUM(
                CASE
                    WHEN pp.fetch_status = 'ok' AND pp.normalized_price IS NOT NULL
                    THEN 1
                    ELSE 0
                END
            ) AS success_count
        FROM snapshots s
        LEFT JOIN price_points pp ON pp.snapshot_id = s.snapshot_id
        GROUP BY s.snapshot_id
        """
    ).fetchall()
    snapshot_ids = [
        int(row["snapshot_id"])
        for row in rows
        if int(row["total_count"] or 0) == 0
        or (float(row["success_count"] or 0) / float(row["total_count"])) < min_success_rate
    ]
    if not snapshot_ids:
        return 0
    placeholders = ",".join("?" for _ in snapshot_ids)
    con.execute(f"DELETE FROM price_points WHERE snapshot_id IN ({placeholders})", snapshot_ids)
    con.execute(f"DELETE FROM snapshots WHERE snapshot_id IN ({placeholders})", snapshot_ids)
    return len(snapshot_ids)


def summarize_fetch_status(statuses: list[tuple[str, str | None]]) -> tuple[str, str | None]:
    total = len(statuses)
    ok_count = sum(1 for status, _ in statuses if status == "ok")
    missing_count = sum(1 for status, _ in statuses if status == "missing")
    error_count = sum(1 for status, _ in statuses if status == "error")
    first_error = next((error for _, error in statuses if error), None)

    if ok_count == total:
        return "ok", None
    if error_count == total:
        return "error", first_error
    if missing_count == total:
        return "missing", first_error
    summary = f"{ok_count} ok, {missing_count} missing"
    if error_count:
        summary += f", {error_count} error"
    return "partial", summary


def normalize_to_usd(price: float | None, currency: str) -> float | None:
    if price is None:
        return None
    currency = (currency or "USD").upper()
    if currency == "USD":
        return price
    rate = os.getenv(f"FX_{currency}_TO_USD")
    if not rate:
        return None
    try:
        return price * float(rate)
    except ValueError:
        return None


def latest_snapshot() -> sqlite3.Row | None:
    with connect() as con:
        return con.execute(
            "SELECT * FROM snapshots ORDER BY timestamp DESC, snapshot_id DESC LIMIT 1"
        ).fetchone()


def latest_price_points() -> list[sqlite3.Row]:
    snapshot = latest_snapshot()
    if snapshot is None:
        return []
    return price_points_for_snapshot(int(snapshot["snapshot_id"]))


def price_points_for_snapshot(snapshot_id: int) -> list[sqlite3.Row]:
    with connect() as con:
        return list(
            con.execute(
                """
                SELECT pp.*, bi.active, bi.multiplier
                FROM price_points pp
                LEFT JOIN basket_items bi ON bi.item_id = pp.item_id
                WHERE pp.snapshot_id = ?
                ORDER BY pp.marketplace, pp.market_hash_name
                """,
                (snapshot_id,),
            ).fetchall()
        )


def update_latest_missing_price_points(marketplace: str, results: Iterable[PriceResult]) -> int:
    return update_latest_repair_price_points(marketplace, results)


def update_latest_repair_price_points(
    marketplace: str,
    results: Iterable[PriceResult],
    overwrite_market_hash_names: set[str] | None = None,
) -> int:
    snapshot = latest_snapshot()
    if snapshot is None:
        return 0

    overwrite_market_hash_names = overwrite_market_hash_names or set()
    item_map = {row["market_hash_name"]: int(row["item_id"]) for row in get_basket_items()}
    timestamp = snapshot["timestamp"]
    updated_count = 0
    with connect() as con:
        for result in results:
            if result.marketplace != marketplace:
                continue
            normalized_price = normalize_to_usd(result.price, result.currency)
            if result.fetch_status != "ok" or normalized_price is None:
                continue

            existing = con.execute(
                """
                SELECT fetch_status, normalized_price
                FROM price_points
                WHERE snapshot_id = ? AND marketplace = ? AND market_hash_name = ?
                """,
                (snapshot["snapshot_id"], marketplace, result.market_hash_name),
            ).fetchone()
            should_overwrite = result.market_hash_name in overwrite_market_hash_names
            if (
                existing
                and existing["fetch_status"] == "ok"
                and existing["normalized_price"] is not None
                and not should_overwrite
            ):
                continue

            if existing:
                con.execute(
                    """
                    UPDATE price_points
                    SET price = ?,
                        currency = ?,
                        normalized_price = ?,
                        normalized_currency = 'USD',
                        stock_count = ?,
                        fetch_status = ?,
                        error_details = ?,
                        timestamp = ?
                    WHERE snapshot_id = ? AND marketplace = ? AND market_hash_name = ?
                    """,
                    (
                        result.price,
                        result.currency,
                        normalized_price,
                        result.stock_count,
                        result.fetch_status,
                        result.error_details,
                        timestamp,
                        snapshot["snapshot_id"],
                        marketplace,
                        result.market_hash_name,
                    ),
                )
            else:
                con.execute(
                    """
                    INSERT INTO price_points (
                        snapshot_id, marketplace, item_id, market_hash_name,
                        price, currency, normalized_price, normalized_currency,
                        stock_count, fetch_status, error_details, timestamp
                    )
                    VALUES (?, ?, ?, ?, ?, ?, ?, 'USD', ?, ?, ?, ?)
                    """,
                    (
                        snapshot["snapshot_id"],
                        marketplace,
                        item_map.get(result.market_hash_name),
                        result.market_hash_name,
                        result.price,
                        result.currency,
                        normalized_price,
                        result.stock_count,
                        result.fetch_status,
                        result.error_details,
                        timestamp,
                    ),
                )
            updated_count += 1

        refresh_marketplace_status(con, marketplace, int(snapshot["snapshot_id"]), timestamp)
    return updated_count


def sync_sqlite_to_postgres() -> dict[str, int]:
    if not DB_PATH.exists():
        raise RuntimeError(f"Local SQLite database not found: {DB_PATH}")
    if not postgres_database_url():
        raise RuntimeError("DATABASE_URL is not configured.")

    counts = {
        "basket_items": 0,
        "marketplaces": 0,
        "snapshots": 0,
        "price_points": 0,
        "pulled_snapshots": 0,
        "pulled_price_points": 0,
        "update_runs": 0,
        "pulled_update_runs": 0,
    }
    source = sqlite3.connect(DB_PATH)
    source.row_factory = sqlite3.Row
    try:
        with connect_postgres() as target:
            target.executescript(_schema_sql("postgres"))
            _sync_basket_items_to_postgres(source, target, counts)
            _sync_marketplaces_to_postgres(source, target, counts)
            _sync_update_runs_to_postgres(source, target, counts)
            item_map = {
                row["market_hash_name"]: int(row["item_id"])
                for row in target.execute("SELECT item_id, market_hash_name FROM basket_items").fetchall()
            }
            for snapshot in source.execute("SELECT * FROM snapshots ORDER BY timestamp, snapshot_id"):
                target_snapshot_id = _postgres_snapshot_id_for_timestamp(target, snapshot["timestamp"])
                target.execute("DELETE FROM price_points WHERE snapshot_id = ?", (target_snapshot_id,))
                batch = []
                for point in source.execute(
                    "SELECT * FROM price_points WHERE snapshot_id = ? ORDER BY price_point_id",
                    (snapshot["snapshot_id"],),
                ):
                    batch.append(
                        (
                            target_snapshot_id,
                            point["marketplace"],
                            item_map.get(point["market_hash_name"]),
                            point["market_hash_name"],
                            _float_or_none(point["price"]),
                            point["currency"] or "USD",
                            _float_or_none(point["normalized_price"]),
                            point["normalized_currency"] or "USD",
                            _int_or_none(point["stock_count"]),
                            point["fetch_status"],
                            _none_if_blank(point["error_details"]),
                            point["timestamp"],
                        )
                    )
                if batch:
                    target.executemany(
                        """
                        INSERT INTO price_points (
                            snapshot_id, marketplace, item_id, market_hash_name,
                            price, currency, normalized_price, normalized_currency,
                            stock_count, fetch_status, error_details, timestamp
                        )
                        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                        """,
                        batch,
                    )
                counts["snapshots"] += 1
                counts["price_points"] += len(batch)
            _sync_missing_postgres_snapshots_to_sqlite(source, target, counts)
            _sync_missing_postgres_update_runs_to_sqlite(source, target, counts)
            source.commit()
    finally:
        source.close()
    return counts


def _sync_missing_postgres_snapshots_to_sqlite(
    target: sqlite3.Connection,
    source: DbConnection,
    counts: dict[str, int],
) -> None:
    local_timestamps = {
        row["timestamp"]
        for row in target.execute("SELECT timestamp FROM snapshots")
    }
    item_map = {
        row["market_hash_name"]: int(row["item_id"])
        for row in target.execute("SELECT item_id, market_hash_name FROM basket_items")
    }

    for snapshot in source.execute("SELECT * FROM snapshots ORDER BY timestamp, snapshot_id").fetchall():
        timestamp = snapshot["timestamp"]
        if timestamp in local_timestamps:
            continue

        cur = target.execute("INSERT INTO snapshots(timestamp) VALUES (?)", (timestamp,))
        local_snapshot_id = int(cur.lastrowid)
        batch = []
        status_by_marketplace: dict[str, list[tuple[str, str | None]]] = {}
        for point in source.execute(
            "SELECT * FROM price_points WHERE snapshot_id = ? ORDER BY price_point_id",
            (snapshot["snapshot_id"],),
        ).fetchall():
            status_by_marketplace.setdefault(point["marketplace"], []).append(
                (point["fetch_status"], point["error_details"])
            )
            batch.append(
                (
                    local_snapshot_id,
                    point["marketplace"],
                    item_map.get(point["market_hash_name"]),
                    point["market_hash_name"],
                    _float_or_none(point["price"]),
                    point["currency"] or "USD",
                    _float_or_none(point["normalized_price"]),
                    point["normalized_currency"] or "USD",
                    _int_or_none(point["stock_count"]),
                    point["fetch_status"],
                    _none_if_blank(point["error_details"]),
                    point["timestamp"],
                )
            )

        if batch:
            target.executemany(
                """
                INSERT INTO price_points (
                    snapshot_id, marketplace, item_id, market_hash_name,
                    price, currency, normalized_price, normalized_currency,
                    stock_count, fetch_status, error_details, timestamp
                )
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                batch,
            )
        for marketplace, statuses in status_by_marketplace.items():
            status, error = summarize_fetch_status(statuses)
            target.execute(
                """
                UPDATE marketplaces
                SET last_status = ?, last_error = ?, updated_at = ?
                WHERE name = ?
                """,
                (status, error, timestamp, marketplace),
            )
        local_timestamps.add(timestamp)
        counts["pulled_snapshots"] += 1
        counts["pulled_price_points"] += len(batch)


def _sync_update_runs_to_postgres(source: sqlite3.Connection, target: DbConnection, counts: dict[str, int]) -> None:
    for row in source.execute("SELECT * FROM update_runs ORDER BY started_at, update_run_id"):
        existing = target.execute(
            """
            SELECT update_run_id
            FROM update_runs
            WHERE source = ? AND started_at = ? AND finished_at = ?
            LIMIT 1
            """,
            (row["source"], row["started_at"], row["finished_at"]),
        ).fetchone()
        if existing:
            target.execute(
                """
                UPDATE update_runs
                SET duration_seconds = ?,
                    status = ?,
                    snapshot_id = ?,
                    success_rate = ?,
                    error_details = ?
                WHERE update_run_id = ?
                """,
                (
                    _float_or_none(row["duration_seconds"]) or 0.0,
                    row["status"],
                    _int_or_none(row["snapshot_id"]),
                    _float_or_none(row["success_rate"]),
                    _none_if_blank(row["error_details"]),
                    existing["update_run_id"],
                ),
            )
        else:
            target.execute(
                """
                INSERT INTO update_runs (
                    source, started_at, finished_at, duration_seconds, status,
                    snapshot_id, success_rate, error_details
                )
                VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    row["source"],
                    row["started_at"],
                    row["finished_at"],
                    _float_or_none(row["duration_seconds"]) or 0.0,
                    row["status"],
                    _int_or_none(row["snapshot_id"]),
                    _float_or_none(row["success_rate"]),
                    _none_if_blank(row["error_details"]),
                ),
            )
        counts["update_runs"] += 1


def _sync_missing_postgres_update_runs_to_sqlite(
    target: sqlite3.Connection,
    source: DbConnection,
    counts: dict[str, int],
) -> None:
    for row in source.execute("SELECT * FROM update_runs ORDER BY started_at, update_run_id").fetchall():
        existing = target.execute(
            """
            SELECT update_run_id
            FROM update_runs
            WHERE source = ? AND started_at = ? AND finished_at = ?
            LIMIT 1
            """,
            (row["source"], row["started_at"], row["finished_at"]),
        ).fetchone()
        if existing:
            continue
        target.execute(
            """
            INSERT INTO update_runs (
                source, started_at, finished_at, duration_seconds, status,
                snapshot_id, success_rate, error_details
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                row["source"],
                row["started_at"],
                row["finished_at"],
                _float_or_none(row["duration_seconds"]) or 0.0,
                row["status"],
                _int_or_none(row["snapshot_id"]),
                _float_or_none(row["success_rate"]),
                _none_if_blank(row["error_details"]),
            ),
        )
        counts["pulled_update_runs"] += 1


def _sync_basket_items_to_postgres(source: sqlite3.Connection, target: DbConnection, counts: dict[str, int]) -> None:
    for row in source.execute("SELECT * FROM basket_items ORDER BY item_id"):
        target.execute(
            """
            INSERT INTO basket_items (
                market_hash_name, active, multiplier, notes, source_rank,
                source_amount, price_compare_url, priceempire_url, steamanalyst_url,
                marketplace_links_json, created_at
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT(market_hash_name) DO UPDATE SET
                active = excluded.active,
                multiplier = excluded.multiplier,
                notes = excluded.notes,
                source_rank = excluded.source_rank,
                source_amount = excluded.source_amount,
                price_compare_url = excluded.price_compare_url,
                priceempire_url = excluded.priceempire_url,
                steamanalyst_url = excluded.steamanalyst_url,
                marketplace_links_json = excluded.marketplace_links_json
            """,
            (
                row["market_hash_name"],
                _int_or_default(row["active"], 1),
                _int_or_default(row["multiplier"], 1),
                row["notes"] or "",
                _int_or_none(row["source_rank"]),
                _float_or_none(row["source_amount"]),
                _none_if_blank(row["price_compare_url"]),
                _none_if_blank(row["priceempire_url"]),
                _none_if_blank(row["steamanalyst_url"]),
                _none_if_blank(row["marketplace_links_json"]),
                row["created_at"] or utc_now_iso(),
            ),
        )
        counts["basket_items"] += 1


def _sync_marketplaces_to_postgres(source: sqlite3.Connection, target: DbConnection, counts: dict[str, int]) -> None:
    for row in source.execute("SELECT * FROM marketplaces ORDER BY adapter_key"):
        target.execute(
            """
            INSERT INTO marketplaces (
                adapter_key, name, enabled, is_baseline, requires_credentials,
                last_status, last_error, updated_at
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT(adapter_key) DO UPDATE SET
                name = excluded.name,
                enabled = excluded.enabled,
                is_baseline = excluded.is_baseline,
                requires_credentials = excluded.requires_credentials,
                last_status = excluded.last_status,
                last_error = excluded.last_error,
                updated_at = excluded.updated_at
            """,
            (
                row["adapter_key"],
                row["name"],
                _int_or_default(row["enabled"], 1),
                _int_or_default(row["is_baseline"], 0),
                _int_or_default(row["requires_credentials"], 0),
                _none_if_blank(row["last_status"]),
                _none_if_blank(row["last_error"]),
                _none_if_blank(row["updated_at"]),
            ),
        )
        counts["marketplaces"] += 1


def _postgres_snapshot_id_for_timestamp(target: DbConnection, timestamp: str) -> int:
    row = target.execute("SELECT snapshot_id FROM snapshots WHERE timestamp = ? LIMIT 1", (timestamp,)).fetchone()
    if row:
        return int(row["snapshot_id"])
    cur = target.execute("INSERT INTO snapshots(timestamp) VALUES (?) RETURNING snapshot_id", (timestamp,))
    return int(cur.fetchone()["snapshot_id"])


def _none_if_blank(value):
    if value is None:
        return None
    text = str(value)
    return None if text.strip() == "" else value


def _int_or_none(value) -> int | None:
    try:
        if value is None or str(value).strip() == "":
            return None
        return int(float(value))
    except (TypeError, ValueError):
        return None


def _int_or_default(value, default: int) -> int:
    parsed = _int_or_none(value)
    return default if parsed is None else parsed


def _float_or_none(value) -> float | None:
    try:
        if value is None or str(value).strip() == "":
            return None
        return float(value)
    except (TypeError, ValueError):
        return None


def refresh_marketplace_status(
    con: DbConnection,
    marketplace: str,
    snapshot_id: int,
    timestamp: str,
) -> None:
    rows = con.execute(
        """
        SELECT fetch_status, error_details
        FROM price_points
        WHERE snapshot_id = ? AND marketplace = ?
        """,
        (snapshot_id, marketplace),
    ).fetchall()
    if not rows:
        return
    status, error = summarize_fetch_status(
        [(row["fetch_status"], row["error_details"]) for row in rows]
    )
    con.execute(
        """
        UPDATE marketplaces
        SET last_status = ?, last_error = ?, updated_at = ?
        WHERE name = ?
        """,
        (status, error, timestamp, marketplace),
    )


def history_totals(since_iso: str | None = None) -> list[sqlite3.Row]:
    params: list[str] = []
    where = "WHERE bi.active = 1"
    if since_iso:
        where += " AND s.timestamp >= ?"
        params.append(since_iso)
    multiplier_expr = (
        "LEAST(GREATEST(COALESCE(bi.multiplier, 1), 1), 1000)"
        if using_postgres()
        else "MIN(MAX(COALESCE(bi.multiplier, 1), 1), 1000)"
    )
    with connect() as con:
        return list(
            con.execute(
                f"""
                WITH snapshot_marketplaces AS (
                    SELECT DISTINCT snapshot_id, marketplace
                    FROM price_points
                ),
                totals AS (
                    SELECT
                        s.snapshot_id,
                        s.timestamp,
                        sm.marketplace,
                        SUM(
                            COALESCE(
                                pp.normalized_price,
                                CASE
                                    WHEN sm.marketplace IN ('Buff163', 'YouPin')
                                    THEN COALESCE(c5game.normalized_price, baseline.normalized_price)
                                    WHEN sm.marketplace != ? THEN baseline.normalized_price
                                    ELSE NULL
                                END
                            ) * {multiplier_expr}
                        ) AS total_cost,
                        COUNT(pp.normalized_price) AS available_count,
                        SUM(
                            CASE
                                WHEN sm.marketplace != ?
                                    AND pp.normalized_price IS NULL
                                    AND (
                                        baseline.normalized_price IS NOT NULL
                                        OR (
                                            sm.marketplace IN ('Buff163', 'YouPin')
                                            AND c5game.normalized_price IS NOT NULL
                                        )
                                    )
                                THEN 1
                                ELSE 0
                            END
                        ) AS fallback_count
                    FROM snapshots s
                    JOIN snapshot_marketplaces sm ON sm.snapshot_id = s.snapshot_id
                    JOIN basket_items bi ON bi.active = 1
                    LEFT JOIN price_points pp
                        ON pp.snapshot_id = s.snapshot_id
                        AND pp.marketplace = sm.marketplace
                        AND pp.item_id = bi.item_id
                        AND pp.fetch_status = 'ok'
                        AND pp.normalized_price IS NOT NULL
                    LEFT JOIN price_points baseline
                        ON baseline.snapshot_id = s.snapshot_id
                        AND baseline.marketplace = ?
                        AND baseline.item_id = bi.item_id
                        AND baseline.fetch_status = 'ok'
                        AND baseline.normalized_price IS NOT NULL
                    LEFT JOIN price_points c5game
                        ON c5game.snapshot_id = s.snapshot_id
                        AND c5game.marketplace = 'C5Game'
                        AND c5game.item_id = bi.item_id
                        AND c5game.fetch_status = 'ok'
                        AND c5game.normalized_price IS NOT NULL
                    {where}
                    GROUP BY s.snapshot_id, s.timestamp, sm.marketplace
                )
                SELECT *
                FROM totals
                WHERE total_cost IS NOT NULL
                ORDER BY timestamp, marketplace
                """,
                [BASELINE_MARKETPLACE, BASELINE_MARKETPLACE, BASELINE_MARKETPLACE, *params],
            ).fetchall()
        )
